import { ServiceBase, ServiceKey, type IServiceProvider } from '@pragmatic-lab/mural/runtime'
import { check, toJSON, Severity, type TodlDocument } from '@pragmatic-lab/todl'

import {
    PROJECT_MANIFEST_FILENAME,
    type IProjectFactory,
    type IPresentationProjectFactory,
    type IPublishableProjectFactory,
    type ProjectFileFormat,
    type ProjectManifestEnvelope,
    type PublishResult,
} from '../../../services/projects/project-factory.js'
import { Project, ProjectNode, type ProjectNodeKind } from '../../../services/projects/project.js'
import { compareStorageEntries, type IStorage, type StorageEntry } from '../../../services/storage/storage.js'
import { ensureMetaModelsBackend } from './meta-models-backend.js'
import { ensureScaffold } from './meta-model-scaffold.js'
import { collectTodlSources, extname, joinRel } from './todl-sources.js'
import { generatePresentationMu } from './presentation-generator.js'
import { publishPresentation } from './presentation-publisher.js'
import { projectAnnotations } from './annotation-projection.js'
import type { MetaModelManifestFile } from './meta-model-manifest-loader.js'

// The 'meta-model' project type's factory — the meta-model module's contribution
// to the generic ProjectExplorerService (declared via `.projectFactories:` and
// resolved through the ProjectFactoryRegistry). It owns the project lifecycle;
// the `.todl` FILE format is edited by TodlDocumentFactory (resolved by
// extension) — editors own files, this factory owns the project.
//
// It is also publishable (IPublishableProjectFactory): publish validates every
// `.todl` in the project with TODL's check(), and — if clean — writes the
// compiled TodlDocument JSON plus the raw sources into the shared meta-models
// backend under `<id>/<modelVersion>/`, where other project types consume it.
//
// All persistence flows through the project's IStorage (rooted, project-relative
// paths); the factory never sees an absolute path or the raw file system.
interface MetaModelManifest extends ProjectManifestEnvelope
{
    id:           string   // stable publish identity, defaults to slugify(name)
    modelVersion: string   // published version, defaults to '0.1.0'
}

export class MetaModelProjectFactory extends ServiceBase
    implements IProjectFactory, IPublishableProjectFactory, IPresentationProjectFactory
{
    public static readonly Key = new ServiceKey<MetaModelProjectFactory>('MetaModelProjectFactory')
    public static readonly ProjectType = 'meta-model'

    // The autogenerated presentation dictionary + the folder of author overrides
    // it merges. Only the generated file is ever written by this factory.
    private static readonly PRESENTATION_FILE = 'presentation.generated.mu'
    private static readonly PRESENTATION_DIR = 'presentation'

    public readonly formats: readonly ProjectFileFormat[] = [
        { extension: '.todl', kind: 'todl', displayName: 'TODL Definition' },
    ]

    constructor(provider: IServiceProvider) { super(provider) }

    public async createProject(storage: IStorage, name: string): Promise<Project>
    {
        const manifest: MetaModelManifest = {
            type: MetaModelProjectFactory.ProjectType, name, version: 1,
            id: slugify(name), modelVersion: '0.1.0',
        }
        await storage.WriteText(PROJECT_MANIFEST_FILENAME, JSON.stringify(manifest, null, 2))
        // Lay down the agent-support scaffold (CLAUDE.md + .claude/) so an agent
        // working in the project has the TODL rules + manual from the start.
        await ensureScaffold(storage)
        return this.buildProject(storage, manifest)
    }

    public async openProject(storage: IStorage): Promise<Project>
    {
        const manifest = JSON.parse(await storage.ReadText(PROJECT_MANIFEST_FILENAME)) as MetaModelManifest
        // Self-heal: write any missing scaffold file (never overwrites the
        // author's edits) so existing projects gain it too.
        await ensureScaffold(storage)
        return this.buildProject(storage, manifest)
    }

    public async saveProject(project: Project, storage: IStorage): Promise<void>
    {
        // Preserve the publish identity (id / modelVersion); only the name tracks
        // the project.
        const manifest = JSON.parse(await storage.ReadText(PROJECT_MANIFEST_FILENAME)) as MetaModelManifest
        manifest.name = project.Name
        await storage.WriteText(PROJECT_MANIFEST_FILENAME, JSON.stringify(manifest, null, 2))
    }

    // Validate every `.todl` together; if clean, emit the compiled model + copy
    // the sources into the meta-models backend under `<id>/<modelVersion>/`.
    public async publish(_project: Project, storage: IStorage, provider: IServiceProvider): Promise<PublishResult>
    {
        const manifest = JSON.parse(await storage.ReadText(PROJECT_MANIFEST_FILENAME)) as MetaModelManifest
        const sources = await collectTodlSources(storage)
        if (sources.length === 0) return { ok: false, message: 'Nothing to publish — the project has no .todl files.' }

        const { model, diagnostics } = check(sources)
        const errors = diagnostics.filter((d) => d.severity === Severity.Error)
        if (errors.length > 0)
            return { ok: false, message: `Publish blocked: ${errors.length} error(s). Fix them first.` }

        const doc = toJSON(model)
        const dest = ensureMetaModelsBackend(provider)
        const base = `${manifest.id}/${manifest.modelVersion}`
        await dest.WriteText(`${base}/model.json`, JSON.stringify(doc, null, 2))
        for (const s of sources) await dest.WriteText(`${base}/src/${s.uri}`, s.text)
        // Ship a thin package descriptor (identity + package-level annotations) so
        // Plexus can understand the package without parsing model.json.
        const PACKAGE_NODE = 'package'
        const manifestFile: MetaModelManifestFile = {
            id: manifest.id, version: manifest.modelVersion, name: manifest.name ?? manifest.id,
            annotations: projectAnnotations(doc, PACKAGE_NODE),
        }
        await dest.WriteText(`${base}/manifest.json`, JSON.stringify(manifestFile, null, 2))
        // Keep the project's presentation dictionary current with what was published.
        await this.writePresentation(storage, doc)
        // Ship a self-contained presentation payload into the backend so a
        // consumer can instantiate the entity templates (sub-project B).
        const authorDicts = await this.scanAuthorDicts(storage)
        const pres = await publishPresentation(storage, dest, base, doc, authorDicts)
        return {
            ok: true,
            message: `Published ${manifest.id}@${manifest.modelVersion} (${sources.length} file(s), `
                + `presentation: ${pres.templates} template(s), ${pres.icons} icon(s)).`,
        }
    }

    // Capability entry point (the "Generate Presentation" command): compile the
    // project's .todl to a model, then write the presentation dictionary. No .todl
    // → no-op; a TODL error → leave the file untouched (the Problems dock already
    // surfaces the errors).
    public async regeneratePresentation(storage: IStorage): Promise<void>
    {
        const sources = await collectTodlSources(storage)
        if (sources.length === 0) return
        const { model, diagnostics } = check(sources)
        if (diagnostics.some((d) => d.severity === Severity.Error)) return
        await this.writePresentation(storage, toJSON(model))
    }

    // Write presentation.generated.mu from an already-compiled document. Scans the
    // presentation/ folder for author dictionaries to merge (by their resources
    // block name). Shared by regeneratePresentation and publish (which passes its
    // own compiled doc, avoiding a second compile).
    private async writePresentation(storage: IStorage, doc: TodlDocument): Promise<void>
    {
        const authorDicts = await this.scanAuthorDicts(storage)
        const source = generatePresentationMu(doc, authorDicts)
        await storage.WriteText(MetaModelProjectFactory.PRESENTATION_FILE, source)
    }

    // The `resources <Name>` identifiers declared in presentation/*.mu, so the
    // generated dictionary can `merge` each (one dictionary per file, by
    // convention). Missing folder → []. Sorted for deterministic output.
    private async scanAuthorDicts(storage: IStorage): Promise<string[]>
    {
        let entries: readonly StorageEntry[]
        try { entries = await storage.List(MetaModelProjectFactory.PRESENTATION_DIR) }
        catch { return [] }
        const names: string[] = []
        for (const e of entries) {
            if (e.IsDirectory || !e.Name.endsWith('.mu')) continue
            const text = await storage.ReadText(`${MetaModelProjectFactory.PRESENTATION_DIR}/${e.Name}`)
            const m = /\bresources\s+([A-Za-z_][A-Za-z0-9_]*)/.exec(text)
            if (m) names.push(m[1])
        }
        return names.sort()
    }

    private async buildProject(storage: IStorage, manifest: MetaModelManifest): Promise<Project>
    {
        const rootName = basename(storage.Root)
        const root = new ProjectNode(rootName, '', 'folder')   // the root node's path is ''
        await this.populate(storage, root)
        return new Project(manifest.type, manifest.name ?? rootName, storage.Root, root)
    }

    // Recursively fill a folder node's children from storage. The manifest file
    // is hidden; `.todl` files are marked openable (kind 'todl'). Node paths are
    // project-relative (POSIX `/`); the root node's path is ''.
    private async populate(storage: IStorage, node: ProjectNode): Promise<void>
    {
        const entries = [...await storage.List(node.Path)].sort(compareStorageEntries)
        for (const e of entries) {
            if (node.Path === '' && e.Name === PROJECT_MANIFEST_FILENAME) continue
            const childPath = joinRel(node.Path, e.Name)
            const kind: ProjectNodeKind = e.IsDirectory
                ? 'folder'
                : extname(e.Name) === '.todl' ? 'todl' : 'file'
            const child = new ProjectNode(e.Name, childPath, kind)
            node.Children.Add(child)
            if (e.IsDirectory) await this.populate(storage, child)
        }
    }
}

// ── helpers ──
function slugify(name: string): string
{
    return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'meta-model'
}

function basename(p: string): string
{
    const parts = p.split(/[\\/]/)
    return parts[parts.length - 1] || p
}
