// presentation-generator.ts — pure emitter for a meta-model's presentation
// resource dictionary. No I/O, no mural import; deterministic text only. All
// model/filesystem access lives in the factory that calls this.

import type { TodlDocument, JsonNode } from '@pragmatic-lab/todl'

// The ontology-tier typeOf values presented as first-class entities. `field`
// (concept attributes) is intentionally excluded.
export enum OntologyKind
{
    Concept = 'concept',
    Relationship = 'relationship',
    Taxonomy = 'taxonomy',
    Primitive = 'primitive',
}

const ONTOLOGY_KINDS = new Set<string>(Object.values(OntologyKind))

// Ontology-tier nodes that are presentable entities (concept/relationship/
// taxonomy/primitive), in model order.
export function ontologyEntities(model: TodlDocument): JsonNode[]
{
    return model.nodes.filter((n) => n.tier === 'Ontology' && ONTOLOGY_KINDS.has(n.typeOf))
}

// Distinct `attrs.icon` values across every node (Ontology + Instance), sorted —
// the SVGs the generated dictionary `include`s so they are available as geometry
// resources to generated templates and author templates alike.
export function distinctIcons(model: TodlDocument): string[]
{
    const set = new Set<string>()
    for (const n of model.nodes) {
        const icon = n.attrs['icon']
        if (typeof icon === 'string' && icon.length > 0) set.add(icon)
    }
    return [...set].sort()
}

// Emit the presentation resource dictionary source. Deterministic: icons sorted,
// entities in model order, one `include` per distinct icon. `authorOverrideDicts`
// are compiled-dictionary identifiers to `merge` last (author keys win); [] emits
// no merge block.
export function generatePresentationMu(model: TodlDocument, authorOverrideDicts: readonly string[]): string
{
    const includes = distinctIcons(model).map((p) => `    include "${p}" as ${iconKey(p)}`)
    const templates = ontologyEntities(model).map(entityTemplate)
    const merges = authorOverrideDicts.map((d) => `    merge ${d}`)

    const lines: string[] = [
        '// presentation.generated.mu — AUTOGENERATED. Do not edit.',
        '// Regenerated from model.json. Author customisation goes in presentation/*.mu.',
        '',
        'resources MetaModelPresentation {',
        '',
        '    // --- Icons: one geometry per distinct icon referenced by the model. ---',
        ...includes,
        '',
        '    // --- Entity templates: one per ontology entity, keyed "mm:<id>". ---',
        ...templates,
    ]
    if (merges.length > 0) {
        lines.push('', '    // --- Author overrides (merged last; author keys win). ---', ...merges)
    }
    lines.push('}', '')
    return lines.join('\n')
}

// One entity's DataTemplate. Icon + label when the node carries an attrs.icon,
// else a label-only box. Label = attrs.label ?? humanize(id). Keyed "mm:<id>" so
// a consumer resolves an entity to its template by id.
function entityTemplate(n: JsonNode): string
{
    const icon = n.attrs['icon']
    const label = typeof n.attrs['label'] === 'string' ? String(n.attrs['label']) : humanize(n.id)
    const labelBlock = `TextBlock [ Text = "${escapeMu(label)}", Style = @BodyMedium, Foreground = @OnSurface ]`

    const body = (typeof icon === 'string' && icon.length > 0)
        ? [
            `            StackPanel [ Orientation = Horizontal, VerticalAlignment = Center ] {`,
            `                Shape [ Geometry = @${iconKey(icon)}, Fill = @OnSurfaceVariant, Width = 16, Height = 16, Margin = (0,0,6,0) ]`,
            `                ${labelBlock}`,
            `            }`,
          ]
        : [`            ${labelBlock}`]

    return [
        `    DataTemplate x:key="mm:${n.id}" [ DataType = MetaModelEntity ] {`,
        `        Border [ Background = @SurfaceContainerHigh, CornerRadius = 6, Padding = (8,6,8,6) ] {`,
        ...body,
        `        }`,
        `    }`,
    ].join('\n')
}

// Escape a string for a double-quoted mural attribute value.
function escapeMu(s: string): string { return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') }

// "resources/actor-internal.svg" → "mm_icon_actor_internal". Strips the
// directory + extension, lowercases, and replaces every non-identifier run with
// a single '_', so distinct paths yield distinct keys usable as a mural resource
// key (`@mm_icon_…`).
export function iconKey(path: string): string
{
    const stem = path.replace(/^.*\//, '').replace(/\.[^.]+$/, '')
    const slug = stem.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '')
    return `mm_icon_${slug}`
}

// "app-component" → "App Component". Splits on '-'/'.'/'_' and title-cases each
// word. Used as the fallback label when an entity declares no attrs.label.
export function humanize(id: string): string
{
    return id.split(/[-._]/).filter(Boolean)
        .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
        .join(' ')
}
